export default {
  THEMATIC_BREAK: 'thematicBreak',
  HTML: 'html',
  YAML: 'yaml',
  TABLE: 'table',
  TABLE_CELL: 'tableCell',
  TABLE_HEADER: 'tableRow',
  TABLE_ROW: 'tableRow',
  PARAGRAPH: 'paragraph',
  TEXT: 'text',
  CODE: 'code',
  LIST: 'list',
  LIST_ITEM: 'listItem',
  DEFINITION: 'definition',
  FOOTNOTE_DEFINITION: 'footnoteDefinition',
  HEADING: 'heading',
  BLOCKQUOTE: 'blockquote',
  LINK: 'link',
  IMAGE: 'image',
  FOOTNOTE: 'footnote',
  STRONG: 'strong',
  EMPHASIS: 'emphasis',
  DELETE: 'delete',
  INLINE_CODE: 'inlineCode',
  BREAK: 'break',
  ROOT: 'root',
}
